'use client';

import { usePathname } from 'next/navigation';

type RuleCopy = {
  label: string;
  title: string;
  paragraphs: string[];
};

const copies: Record<string, RuleCopy> = {
  en: {
    label: 'Gameplay clarification · September 10, 2026',
    title: 'Banking, credit, FX, stocks and crypto are virtual game systems',
    paragraphs: [
      `TycoonX banking, savings, credit, FX, stocks and crypto are fictional simulation mechanics, not real bank deposits, securities, investments, legal tender or cryptocurrency assets. Normal interest, borrowing, late payments, collateral consequences, bankruptcy, trades, gains and losses are gameplay outcomes and are not automatically misconduct. Current rates, credit rules, collateral values, cooldowns, fees, spreads and market formulas may be rebalanced prospectively for legitimate game reasons, subject to any mandatory notice, change, conformity or termination rights that apply. No displayed yield, quote, chart or trend guarantees future performance.`,
      `Do not use modified clients, direct APIs, controlled accounts, fabricated holdings or transaction/history records, wash or circular trading, replay/race bugs, unauthorized automation, price-update functions or other technical weaknesses to create value, alter debt or collateral state, manipulate prices, bypass limits, hide exploit proceeds or facilitate prohibited real-money trading. TycoonX-operated price automation is an intended game mechanic and is not player botting. A large gain, loss, trade, debt or unusual market movement alone is not proof of abuse, and server acceptance caused by an authorization or validation defect does not by itself make knowingly manipulated state legitimate.`,
      `In-game debt may affect eligible virtual gameplay assets under the rules then in force, but ordinary gameplay debt does not by itself make unrelated valid purchased Diamonds, one-time 30-Day VIP or Lifetime VIP collateral. Diamonds used for an eligible FX-slot unlock purchase the in-game slot entitlement, not a promise of investment profit. Stale screens, client-writable records and convenience notifications are not automatically conclusive evidence. CK-Labs should distinguish outages, defects, accidental one-off actions and account compromise from knowing or repeated exploitation, reconcile directly affected invalid state proportionately, and preserve all mandatory consumer and other non-waivable rights.`,
    ],
  },
  tr: {
    label: 'Oynanış açıklaması · 10 Eylül 2026',
    title: 'Banka, kredi, döviz, hisse ve kripto sistemleri oyun içidir',
    paragraphs: [
      `TycoonX içindeki banka, birikim, kredi, döviz, hisse ve kripto özellikleri gerçek banka mevduatı, menkul kıymet, yatırım, yasal para veya gerçek kripto varlığı değil, tamamen kurgusal simülasyon mekanikleridir. Normal faiz getirisi, borçlanma, gecikme, teminat sonucu, iflas, alım satım, kazanç ve kayıp oyunun parçasıdır ve tek başına kural ihlali sayılmaz. Faizler, kredi kuralları, teminat değerleri, bekleme süreleri, ücretler, makaslar ve piyasa formülleri geçerli oyun nedenleriyle ileriye dönük dengelenebilir; zorunlu bildirim, değişiklik, uygunluk ve fesih hakları saklıdır. Ekrandaki getiri, teklif, grafik veya trend gelecekteki sonucu garanti etmez.`,
      `Değer üretmek, borç veya teminat durumunu değiştirmek, fiyatları manipüle etmek, sınırları aşmak, exploit gelirini gizlemek ya da yasak gerçek para ticaretini kolaylaştırmak için değiştirilmiş istemci, doğrudan API, kontrol ettiğiniz hesaplar, uydurma portföy veya işlem/geçmiş kayıtları, wash/circular trade, replay/race hataları, izinsiz otomasyon, fiyat güncelleme işlevleri veya başka teknik açıklar kullanmayın. TycoonX tarafından çalıştırılan fiyat otomasyonu normal oyun mekaniğidir ve oyuncu botu değildir. Büyük kazanç, kayıp, işlem, borç veya sıra dışı piyasa hareketi tek başına kötüye kullanım kanıtı değildir; bir yetkilendirme ya da doğrulama hatasının sunucu isteğini kabul etmesi de bilerek manipüle edilmiş durumu meşru hale getirmez.`,
      `Oyun içi borç, o sırada geçerli kurallara göre uygun sanal oyun varlıklarını etkileyebilir; ancak sıradan oyun borcu tek başına ilgisiz ve geçerli şekilde satın alınmış Diamonds, tek seferlik 30 Günlük VIP veya Lifetime VIP'ı teminat yapmaz. Uygun bir döviz slotu açmak için kullanılan Diamonds, yatırım kazancı vaadi değil oyun içi slot hakkı sağlar. Eski ekranlar, istemciden yazılabilen kayıtlar ve kolaylık bildirimleri tek başına kesin kanıt değildir. CK-Labs kesintileri, teknik hataları, tek seferlik kazaları ve hesap ele geçirilmesini bilinçli veya tekrarlı exploit kullanımından ayırmalı, doğrudan etkilenen geçersiz durumu orantılı biçimde düzeltmeli ve vazgeçilemeyen tüketici haklarını korumalıdır.`,
    ],
  },
  de: {
    label: 'Gameplay-Klarstellung · 10. September 2026',
    title: 'Bank, Kredit, Devisen, Aktien und Krypto sind virtuelle Spielsysteme',
    paragraphs: [
      `Bank, Sparen, Kredit, Devisen, Aktien und Krypto in TycoonX sind fiktive Simulationsmechaniken und keine echten Bankeinlagen, Wertpapiere, Geldanlagen, gesetzlichen Zahlungsmittel oder realen Kryptowerte. Reguläre Zinsen, Kredite, verspätete Zahlungen, Folgen für Sicherheiten, Insolvenz, Handel, Gewinne und Verluste sind Spielereignisse und nicht automatisch ein Regelverstoß. Zinssätze, Kreditregeln, Sicherheitenwerte, Cooldowns, Gebühren, Spreads und Marktformeln können aus sachlichen Spielgründen für die Zukunft angepasst werden; zwingende Informations-, Änderungs-, Vertragsmäßigkeits- und Beendigungsrechte bleiben unberührt. Angezeigte Renditen, Kurse, Charts oder Trends garantieren keine zukünftige Entwicklung.`,
      `Verwende keine manipulierten Clients, direkten APIs, von dir kontrollierten Konten, erfundenen Bestände oder Transaktions-/Verlaufsdaten, Wash- oder Kreisgeschäfte, Replay-/Race-Fehler, unerlaubte Automatisierung, Preisaktualisierungsfunktionen oder andere technische Schwachstellen, um Werte zu erzeugen, Schulden oder Sicherheiten zu verändern, Preise zu manipulieren, Grenzen zu umgehen, Exploit-Erlöse zu verschleiern oder verbotenen Echtgeldhandel zu ermöglichen. Die von TycoonX selbst betriebene Preisautomatisierung ist eine vorgesehene Spielmechanik und kein Spieler-Bot. Ein hoher Gewinn oder Verlust, ein großer Handel, hohe Schulden oder eine ungewöhnliche Marktbewegung sind allein kein Missbrauchsnachweis; eine durch einen Berechtigungs- oder Validierungsfehler akzeptierte Serveranfrage macht wissentlich manipulierten Zustand nicht automatisch legitim.`,
      `Spielschulden können nach den jeweils geltenden Regeln geeignete virtuelle Spielwerte betreffen. Sie machen jedoch nicht allein deshalb unabhängig und wirksam gekaufte Diamonds, einmaliges 30-Tage-VIP oder Lifetime VIP zu Sicherheiten. Diamonds für einen berechtigten Devisen-Slot erwerben den Spiel-Slot, nicht die Zusage eines Anlagegewinns. Veraltete Anzeigen, vom Client beeinflussbare Datensätze und Komfort-Benachrichtigungen sind nicht automatisch abschließende Beweise. CK-Labs soll Ausfälle, technische Fehler, einmalige Versehen und kompromittierte Konten von wissentlich oder wiederholt ausgenutzten Schwachstellen unterscheiden, unmittelbar betroffenen ungültigen Zustand verhältnismäßig berichtigen und zwingende Verbraucherrechte sowie sonstige unabdingbare Rechte wahren.`,
    ],
  },
  es: {
    label: 'Aclaración de juego · 10 de septiembre de 2026',
    title: 'La banca, el crédito, las divisas, las acciones y las criptos son sistemas virtuales',
    paragraphs: [
      `La banca, el ahorro, el crédito, las divisas, las acciones y las criptos de TycoonX son mecánicas ficticias de simulación, no depósitos bancarios, valores, inversiones, moneda de curso legal ni criptoactivos reales. Los intereses normales, los préstamos, los retrasos de pago, las consecuencias sobre garantías, la quiebra, las operaciones, las ganancias y las pérdidas forman parte del juego y no constituyen por sí solos una infracción. Los tipos, reglas de crédito, valores de garantía, esperas, comisiones, diferenciales y fórmulas de mercado pueden ajustarse hacia el futuro por motivos legítimos del juego, respetando los derechos obligatorios de información, modificación, conformidad o resolución que correspondan. Ninguna rentabilidad, cotización, gráfica o tendencia mostrada garantiza resultados futuros.`,
      `No utilices clientes modificados, APIs directas, cuentas bajo tu control, posiciones o historiales de operaciones inventados, operaciones circulares o de lavado, fallos de repetición o carrera, automatización no autorizada, funciones de actualización de precios u otras debilidades técnicas para crear valor, alterar deudas o garantías, manipular precios, eludir límites, ocultar beneficios de exploits o facilitar comercio prohibido con dinero real. La automatización de precios gestionada por TycoonX es una mecánica prevista del juego, no un bot del jugador. Una gran ganancia o pérdida, una operación grande, una deuda elevada o un movimiento inusual del mercado no prueban por sí solos un abuso; que el servidor acepte una petición por un fallo de autorización o validación tampoco legitima un estado manipulado conscientemente.`,
      `La deuda del juego puede afectar a los activos virtuales aptos conforme a las reglas vigentes, pero por sí sola no convierte en garantía Diamonds comprados válidamente y no relacionados, el VIP de 30 días de un solo pago ni Lifetime VIP. Los Diamonds usados para desbloquear una ranura de divisas apta adquieren ese derecho dentro del juego, no una promesa de rentabilidad. Pantallas desactualizadas, registros modificables desde el cliente y notificaciones informativas no son necesariamente prueba concluyente. CK-Labs debe diferenciar caídas del servicio, defectos, actos accidentales aislados y cuentas comprometidas de la explotación consciente o repetida, corregir de forma proporcionada el estado inválido directamente afectado y respetar todos los derechos imperativos del consumidor y demás derechos irrenunciables.`,
    ],
  },
  es_MX: {
    label: 'Aclaración de juego · 10 de septiembre de 2026',
    title: 'Banco, crédito, divisas, acciones y cripto son sistemas virtuales del juego',
    paragraphs: [
      `El banco, los ahorros, el crédito, las divisas, las acciones y las criptomonedas de TycoonX son mecánicas ficticias de simulación. No son depósitos bancarios, valores, inversiones, moneda de curso legal ni criptoactivos reales. Intereses normales, préstamos, pagos atrasados, consecuencias sobre garantías, bancarrota, operaciones, ganancias y pérdidas son resultados del juego y no implican automáticamente una infracción. Tasas, reglas de crédito, valores de garantía, tiempos de espera, comisiones, spreads y fórmulas de mercado pueden ajustarse hacia el futuro por razones legítimas del juego, respetando cualquier derecho obligatorio de aviso, modificación, conformidad o terminación que corresponda. Ningún rendimiento, precio, gráfica o tendencia mostrada garantiza resultados futuros.`,
      `No uses clientes modificados, APIs directas, cuentas que controles, posiciones o historiales de operaciones inventados, operaciones circulares o de lavado, errores de replay/race, automatización no autorizada, funciones de actualización de precios u otras fallas técnicas para crear valor, cambiar deudas o garantías, manipular precios, saltarte límites, ocultar ganancias de exploits o facilitar comercio prohibido con dinero real. La automatización de precios operada por TycoonX es parte normal del juego, no un bot del jugador. Una ganancia o pérdida grande, una operación importante, mucha deuda o un movimiento inusual del mercado no prueban abuso por sí solos; que el servidor acepte una solicitud por una falla de permisos o validación tampoco vuelve legítimo un estado manipulado a sabiendas.`,
      `La deuda dentro del juego puede afectar activos virtuales elegibles conforme a las reglas vigentes, pero no convierte por sí sola en garantía Diamonds comprados válidamente y no relacionados, el VIP único de 30 días ni Lifetime VIP. Los Diamonds usados para desbloquear un espacio elegible de divisas compran ese derecho dentro del juego, no una promesa de ganancia de inversión. Pantallas desactualizadas, registros que el cliente pueda influir y notificaciones informativas no son prueba definitiva por sí mismas. CK-Labs debe distinguir interrupciones, errores técnicos, acciones accidentales aisladas y cuentas comprometidas de exploits conscientes o repetidos, corregir proporcionalmente el estado inválido directamente afectado y respetar todos los derechos obligatorios del consumidor y demás derechos irrenunciables.`,
    ],
  },
  fr: {
    label: 'Précision de gameplay · 10 septembre 2026',
    title: 'Banque, crédit, devises, actions et crypto sont des systèmes virtuels du jeu',
    paragraphs: [
      `La banque, l'épargne, le crédit, les devises, les actions et la crypto dans TycoonX sont des mécanismes fictifs de simulation, et non de vrais dépôts bancaires, titres financiers, investissements, monnaies ayant cours légal ou cryptoactifs. Les intérêts normaux, emprunts, retards, conséquences sur les garanties, faillites, opérations, gains et pertes relèvent du gameplay et ne constituent pas automatiquement une infraction. Les taux, règles de crédit, valeurs des garanties, délais, frais, spreads et formules de marché peuvent être rééquilibrés pour l'avenir pour des raisons légitimes de jeu, sous réserve des droits impératifs applicables en matière d'information, de modification, de conformité ou de résiliation. Aucun rendement, cours, graphique ou tendance affiché ne garantit une performance future.`,
      `N'utilisez pas de client modifié, d'API directe, de comptes que vous contrôlez, de positions ou historiques d'opérations fabriqués, d'opérations circulaires ou de wash trading, de bugs de répétition ou de concurrence, d'automatisation non autorisée, de fonctions de mise à jour des prix ou d'autres failles techniques pour créer de la valeur, modifier une dette ou une garantie, manipuler les prix, contourner une limite, dissimuler les gains d'un exploit ou faciliter un commerce interdit contre de l'argent réel. L'automatisation des prix opérée par TycoonX est un mécanisme prévu du jeu, pas un bot de joueur. Un gain ou une perte important, une grosse opération, une dette élevée ou un mouvement de marché inhabituel ne suffisent pas à prouver un abus; l'acceptation d'une requête par le serveur à cause d'un défaut d'autorisation ou de validation ne rend pas non plus légitime un état sciemment manipulé.`,
      `Une dette en jeu peut affecter les actifs virtuels éligibles selon les règles alors applicables, mais elle ne transforme pas à elle seule des Diamonds valablement achetés et sans lien, un VIP unique de 30 jours ou Lifetime VIP en garantie. Les Diamonds dépensés pour débloquer un emplacement de devises éligible achètent ce droit en jeu, et non une promesse de rendement. Les écrans périmés, données influençables par le client et notifications de commodité ne constituent pas automatiquement des preuves définitives. CK-Labs doit distinguer pannes, défauts techniques, actes accidentels isolés et comptes compromis d'une exploitation consciente ou répétée, corriger proportionnellement l'état invalide directement concerné et préserver tous les droits impératifs des consommateurs et autres droits auxquels il ne peut être renoncé.`,
    ],
  },
  fr_CA: {
    label: 'Précision de jeu · 10 septembre 2026',
    title: 'Banque, crédit, devises, actions et crypto sont des systèmes virtuels',
    paragraphs: [
      `La banque, l'épargne, le crédit, les devises, les actions et la crypto dans TycoonX sont des mécanismes fictifs de simulation, pas de vrais dépôts bancaires, valeurs mobilières, placements, monnaie ayant cours légal ou cryptoactifs. Les intérêts normaux, emprunts, retards de paiement, conséquences sur les garanties, faillites, transactions, gains et pertes font partie du jeu et ne sont pas automatiquement une infraction. Les taux, règles de crédit, valeurs de garantie, délais, frais, écarts et formules de marché peuvent être ajustés pour l'avenir pour des raisons légitimes de jeu, sous réserve des droits impératifs applicables d'information, de modification, de conformité ou de résiliation. Aucun rendement, prix, graphique ou tendance affiché ne garantit les résultats futurs.`,
      `N'utilisez pas de client modifié, d'API directe, de comptes que vous contrôlez, de positions ou historiques fabriqués, de transactions circulaires ou de wash trading, de bogues de répétition ou de course, d'automatisation non autorisée, de fonctions de mise à jour des prix ou d'autres faiblesses techniques pour créer de la valeur, modifier une dette ou une garantie, manipuler les prix, contourner des limites, dissimuler des gains d'exploitation ou faciliter un commerce interdit contre de l'argent réel. L'automatisation des prix gérée par TycoonX fait partie du jeu; ce n'est pas un bot de joueur. Un gros gain ou une grosse perte, une transaction importante, une dette élevée ou un mouvement de marché inhabituel ne prouvent pas à eux seuls un abus; une requête acceptée à cause d'un défaut d'autorisation ou de validation ne rend pas non plus légitime un état sciemment manipulé.`,
      `Une dette de jeu peut toucher les actifs virtuels admissibles selon les règles alors en vigueur, mais elle ne transforme pas à elle seule des Diamonds achetés validement et sans lien, un VIP unique de 30 jours ou Lifetime VIP en garantie. Les Diamonds dépensés pour déverrouiller une case de devises admissible achètent ce droit dans le jeu, pas une promesse de rendement. Les écrans périmés, données influençables par le client et notifications pratiques ne sont pas automatiquement des preuves concluantes. CK-Labs doit distinguer les pannes, défauts, gestes accidentels isolés et comptes compromis de l'exploitation consciente ou répétée, corriger proportionnellement l'état invalide directement touché et préserver tous les droits impératifs des consommateurs et autres droits auxquels on ne peut renoncer.`,
    ],
  },
  it: {
    label: 'Chiarimento sul gameplay · 10 settembre 2026',
    title: 'Banca, credito, valute, azioni e crypto sono sistemi virtuali di gioco',
    paragraphs: [
      `Banca, risparmi, credito, valute, azioni e crypto in TycoonX sono meccaniche fittizie di simulazione, non veri depositi bancari, titoli, investimenti, moneta avente corso legale o criptoattività reali. Interessi normali, prestiti, ritardi di pagamento, conseguenze sulle garanzie, fallimento, operazioni, guadagni e perdite sono risultati di gioco e non costituiscono automaticamente una violazione. Tassi, regole del credito, valori delle garanzie, tempi di attesa, commissioni, spread e formule di mercato possono essere riequilibrati per il futuro per motivi legittimi di gioco, fatti salvi gli eventuali diritti inderogabili di informazione, modifica, conformità o recesso. Nessun rendimento, prezzo, grafico o trend visualizzato garantisce risultati futuri.`,
      `Non usare client modificati, API dirette, account sotto il tuo controllo, posizioni o cronologie di transazioni inventate, operazioni circolari o wash trading, bug di replay/race, automazioni non autorizzate, funzioni di aggiornamento dei prezzi o altre debolezze tecniche per creare valore, alterare debiti o garanzie, manipolare prezzi, aggirare limiti, occultare proventi da exploit o facilitare commercio vietato con denaro reale. L'automazione dei prezzi gestita da TycoonX è una meccanica prevista del gioco e non è un bot del giocatore. Un grande guadagno o perdita, una grossa operazione, un debito elevato o un movimento insolito del mercato non provano da soli un abuso; anche l'accettazione del server dovuta a un difetto di autorizzazione o convalida non rende legittimo uno stato manipolato consapevolmente.`,
      `Il debito di gioco può incidere sugli asset virtuali idonei secondo le regole in vigore, ma non trasforma di per sé Diamonds validamente acquistati e non correlati, il VIP una tantum di 30 giorni o Lifetime VIP in garanzia. I Diamonds spesi per sbloccare uno slot FX idoneo acquistano quel diritto in gioco, non una promessa di profitto da investimento. Schermate non aggiornate, record influenzabili dal client e notifiche di servizio non sono automaticamente prove conclusive. CK-Labs deve distinguere interruzioni, difetti tecnici, azioni accidentali isolate e account compromessi dallo sfruttamento consapevole o ripetuto, correggere proporzionalmente lo stato non valido direttamente interessato e preservare tutti i diritti inderogabili dei consumatori e gli altri diritti non rinunciabili.`,
    ],
  },
  pt: {
    label: 'Esclarecimento de jogabilidade · 10 de setembro de 2026',
    title: 'Banco, crédito, câmbio, ações e cripto são sistemas virtuais do jogo',
    paragraphs: [
      `O banco, poupanças, crédito, câmbio, ações e cripto em TycoonX são mecânicas fictícias de simulação, não depósitos bancários, valores mobiliários, investimentos, moeda com curso legal ou criptoativos reais. Juros normais, empréstimos, atrasos, consequências sobre garantias, insolvência, operações, ganhos e perdas fazem parte do jogo e não constituem automaticamente uma infração. Taxas, regras de crédito, valores de garantia, tempos de espera, comissões, spreads e fórmulas de mercado podem ser reequilibrados para o futuro por razões legítimas de jogo, sem prejuízo de direitos imperativos de informação, alteração, conformidade ou resolução aplicáveis. Nenhuma rendibilidade, cotação, gráfico ou tendência apresentada garante resultados futuros.`,
      `Não utilizes clientes modificados, APIs diretas, contas sob o teu controlo, posições ou históricos de operações fabricados, transações circulares ou wash trading, falhas de repetição ou corrida, automação não autorizada, funções de atualização de preços ou outras fragilidades técnicas para criar valor, alterar dívida ou garantias, manipular preços, contornar limites, ocultar proveitos de exploits ou facilitar comércio proibido por dinheiro real. A automação de preços operada por TycoonX é uma mecânica prevista do jogo, não um bot do jogador. Um grande ganho ou perda, uma operação avultada, dívida elevada ou um movimento incomum do mercado não prova, por si só, abuso; uma ordem aceite pelo servidor devido a uma falha de autorização ou validação também não torna legítimo um estado conscientemente manipulado.`,
      `A dívida no jogo pode afetar ativos virtuais elegíveis segundo as regras então em vigor, mas não transforma, só por si, Diamonds validamente comprados e sem relação, VIP único de 30 dias ou Lifetime VIP em garantia. Diamonds gastos para desbloquear uma vaga de câmbio elegível compram esse direito no jogo, não uma promessa de lucro de investimento. Ecrãs desatualizados, registos influenciáveis pelo cliente e notificações de conveniência não são automaticamente prova conclusiva. A CK-Labs deve distinguir indisponibilidades, defeitos, atos acidentais isolados e contas comprometidas de exploração consciente ou repetida, corrigir proporcionalmente o estado inválido diretamente afetado e preservar todos os direitos imperativos dos consumidores e outros direitos irrenunciáveis.`,
    ],
  },
  pt_BR: {
    label: 'Esclarecimento de jogabilidade · 10 de setembro de 2026',
    title: 'Banco, crédito, câmbio, ações e cripto são sistemas virtuais do jogo',
    paragraphs: [
      `Banco, poupança, crédito, câmbio, ações e cripto em TycoonX são mecânicas fictícias de simulação, não depósitos bancários, valores mobiliários, investimentos, moeda oficial ou criptoativos reais. Juros normais, empréstimos, atrasos, consequências sobre garantias, falência, operações, ganhos e perdas fazem parte do jogo e não são automaticamente uma infração. Taxas, regras de crédito, valores de garantia, tempos de espera, comissões, spreads e fórmulas de mercado podem ser rebalanceados para o futuro por razões legítimas do jogo, respeitando quaisquer direitos obrigatórios de informação, alteração, conformidade ou encerramento aplicáveis. Nenhum rendimento, cotação, gráfico ou tendência exibida garante resultados futuros.`,
      `Não use clientes modificados, APIs diretas, contas sob seu controle, posições ou históricos de operações fabricados, negociações circulares ou wash trading, falhas de replay/race, automação não autorizada, funções de atualização de preços ou outras falhas técnicas para criar valor, alterar dívida ou garantia, manipular preços, contornar limites, ocultar ganhos de exploits ou facilitar comércio proibido por dinheiro real. A automação de preços operada por TycoonX é uma mecânica prevista do jogo, não um bot do jogador. Um grande ganho ou perda, uma operação alta, muita dívida ou um movimento incomum do mercado não prova abuso sozinho; uma solicitação aceita pelo servidor por falha de autorização ou validação também não torna legítimo um estado conscientemente manipulado.`,
      `A dívida dentro do jogo pode afetar ativos virtuais elegíveis conforme as regras então vigentes, mas não transforma por si só Diamonds comprados validamente e sem relação, VIP único de 30 dias ou Lifetime VIP em garantia. Diamonds gastos para desbloquear um espaço elegível de câmbio compram esse direito no jogo, não uma promessa de lucro de investimento. Telas desatualizadas, registros influenciáveis pelo cliente e notificações informativas não são automaticamente prova conclusiva. A CK-Labs deve distinguir indisponibilidades, defeitos, ações acidentais isoladas e contas comprometidas de exploração consciente ou repetida, corrigir proporcionalmente o estado inválido diretamente afetado e preservar todos os direitos obrigatórios do consumidor e outros direitos irrenunciáveis.`,
    ],
  },
  ru: {
    label: 'Уточнение правил игры · 10 сентября 2026 г.',
    title: 'Банк, кредит, валюты, акции и криптоактивы являются виртуальными системами игры',
    paragraphs: [
      `Банк, сбережения, кредит, валюты, акции и криптоактивы в TycoonX являются вымышленными механиками экономической симуляции, а не настоящими банковскими вкладами, ценными бумагами, инвестициями, законным платёжным средством или реальными криптоактивами. Обычные проценты, займы, просрочки, последствия для залога, банкротство, сделки, прибыль и убытки являются игровыми результатами и сами по себе не означают нарушение. Ставки, кредитные правила, стоимость залога, задержки, комиссии, спреды и рыночные формулы могут изменяться на будущее по обоснованным игровым причинам с сохранением обязательных прав на уведомление, изменения, соответствие или прекращение договора, если они применимы. Показанная доходность, цена, график или тренд не гарантируют будущий результат.`,
      `Не используйте модифицированные клиенты, прямые API, контролируемые вами аккаунты, вымышленные позиции или записи сделок/истории, круговые сделки, wash trading, ошибки replay/race, неразрешённую автоматизацию, функции обновления цен или другие технические слабости для создания ценности, изменения долга или залога, манипуляции ценами, обхода лимитов, сокрытия доходов от эксплойтов или запрещённой торговли за реальные деньги. Автоматическое изменение цен, выполняемое TycoonX, является предусмотренной механикой игры, а не ботом игрока. Крупная прибыль или убыток, большая сделка, высокий долг или необычное движение рынка сами по себе не доказывают злоупотребление; принятие сервером запроса из-за ошибки авторизации или проверки также не делает сознательно подделанное состояние законным.`,
      `Игровой долг может затрагивать подходящие виртуальные активы по действующим на тот момент правилам, но сам по себе он не делает залогом не связанные с ним и действительные покупки Diamonds, разовый 30-дневный VIP или Lifetime VIP. Diamonds, потраченные на доступный дополнительный валютный слот, приобретают право на этот слот в игре, а не обещание инвестиционной прибыли. Устаревший экран, записи, на которые может влиять клиент, и служебные уведомления не являются автоматически окончательным доказательством. CK-Labs должна отличать сбои, технические дефекты, единичные случайные действия и взлом аккаунта от сознательного или повторного использования эксплойта, соразмерно исправлять непосредственно затронутое недействительное состояние и сохранять все обязательные права потребителей и другие неотчуждаемые права.`,
    ],
  },
  ja: {
    label: 'ゲームプレイに関する明確化 · 2026年9月10日',
    title: '銀行・信用・為替・株式・暗号資産はゲーム内の仮想システムです',
    paragraphs: [
      `TycoonXの銀行、貯蓄、信用、為替、株式、暗号資産は架空のシミュレーション機能であり、実際の銀行預金、有価証券、投資、法定通貨、実在する暗号資産ではありません。通常の利息、借入れ、支払遅延、担保への影響、破産、取引、利益や損失はゲーム上の結果であり、それだけで違反にはなりません。金利、信用ルール、担保評価、クールダウン、手数料、スプレッド、市場計算式などは、正当なゲーム上の理由により将来に向けて調整されることがあります。ただし、適用される強行的な通知、変更、契約適合性、終了に関する権利は維持されます。表示される利回り、価格、チャート、トレンドは将来の成果を保証しません。`,
      `価値を不正に作り出したり、債務・担保状態を変更したり、価格を操作したり、制限を回避したり、エクスプロイトで得た利益を隠したり、禁止される現金取引を助けたりする目的で、改造クライアント、直接API、自己管理する複数アカウント、偽造した保有・取引・履歴データ、循環取引やウォッシュ取引、リプレイ/競合バグ、無許可の自動化、価格更新機能その他の技術的弱点を利用しないでください。TycoonXが運用する価格自動更新は意図されたゲーム機能であり、プレイヤーのボット利用ではありません。大きな利益・損失・取引・債務や異常な値動きだけで不正とは判断されません。また、権限・検証の不具合でサーバーが要求を受け付けても、意図的に改ざんした状態が正当になるわけではありません。`,
      `ゲーム内債務はその時点のルールに従って対象となる仮想ゲーム資産に影響する場合がありますが、それだけを理由に無関係で有効に購入されたDiamonds、1回限りの30日VIP、Lifetime VIPが担保になることはありません。対象の為替スロット解除に使うDiamondsはゲーム内スロットの権利を取得するもので、投資利益を約束するものではありません。古い画面、クライアントから影響を受け得る記録、便宜的な通知だけを最終的証拠とはしません。CK-Labsは障害、技術的不具合、単発の偶発行為、アカウント侵害を、故意または反復的な悪用と区別し、直接影響を受けた無効状態を比例的に修正し、消費者の強行的権利その他放棄できない権利を維持します。`,
    ],
  },
  ko: {
    label: '게임플레이 안내 · 2026년 9월 10일',
    title: '은행, 신용, 외환, 주식 및 암호자산은 게임 속 가상 시스템입니다',
    paragraphs: [
      `TycoonX의 은행, 저축, 신용, 외환, 주식 및 암호자산은 허구의 시뮬레이션 기능이며 실제 은행 예금, 증권, 투자상품, 법정통화 또는 실제 암호자산이 아닙니다. 정상적인 이자, 대출, 연체, 담보 결과, 파산, 거래, 이익과 손실은 게임플레이 결과이며 그 자체로 위반이 아닙니다. 금리, 신용 규칙, 담보 가치, 쿨다운, 수수료, 스프레드 및 시장 공식은 정당한 게임상 이유로 향후 조정될 수 있으며, 적용되는 강행적 고지, 변경, 적합성 또는 계약 종료 권리는 그대로 보장됩니다. 화면의 수익률, 시세, 차트 또는 추세는 미래 성과를 보장하지 않습니다.`,
      `가치를 부당하게 생성하거나 부채·담보 상태를 바꾸거나 가격을 조작하거나 제한을 우회하거나 익스플로잇 수익을 숨기거나 금지된 현금 거래를 돕기 위해 변조된 클라이언트, 직접 API, 자신이 통제하는 계정, 조작된 보유량이나 거래/기록, 순환거래 또는 워시 트레이딩, replay/race 버그, 무단 자동화, 가격 업데이트 기능이나 기타 기술적 약점을 사용하지 마세요. TycoonX가 운영하는 가격 자동화는 의도된 게임 기능이며 플레이어 봇 사용이 아닙니다. 큰 이익이나 손실, 큰 거래, 많은 부채 또는 비정상적인 시장 움직임만으로 악용이 입증되지는 않으며, 권한 또는 검증 결함 때문에 서버가 요청을 수락했다고 해서 고의로 조작된 상태가 정당해지는 것도 아닙니다.`,
      `게임 내 부채는 당시 규칙에 따라 해당되는 가상 게임 자산에 영향을 줄 수 있지만, 그것만으로 관련 없는 유효한 구매 Diamonds, 일회성 30일 VIP 또는 Lifetime VIP가 담보가 되지는 않습니다. 해당 외환 슬롯을 열기 위해 사용한 Diamonds는 게임 내 슬롯 권리를 구매하는 것이지 투자 수익을 약속하는 것이 아닙니다. 오래된 화면, 클라이언트가 영향을 줄 수 있는 기록 및 편의 알림만으로 최종 증거가 되지는 않습니다. CK-Labs는 장애, 기술적 결함, 일회성 실수와 계정 탈취를 고의적이거나 반복적인 악용과 구분하고, 직접 영향을 받은 무효 상태를 비례적으로 바로잡으며, 강행적 소비자 권리와 그 밖의 포기할 수 없는 권리를 보장해야 합니다.`,
    ],
  },
  zh: {
    label: '游戏规则说明 · 2026年9月10日',
    title: '银行、信贷、外汇、股票和加密资产都是游戏内虚拟系统',
    paragraphs: [
      `TycoonX中的银行、储蓄、信贷、外汇、股票和加密资产属于虚构的经营模拟机制，并非真实银行存款、证券、投资产品、法定货币或真实加密资产。正常利息、借贷、逾期、抵押后果、破产、交易、盈利和亏损均属于游戏结果，本身并不构成违规。利率、信贷规则、抵押估值、冷却时间、费用、点差和市场公式可因合理的游戏平衡等原因向未来调整，但适用的强制性通知、变更、合规和终止权利不受影响。界面显示的收益率、报价、图表或趋势均不保证未来表现。`,
      `不得利用修改版客户端、直接API、由你控制的账号、伪造持仓或交易/历史记录、循环交易或洗售、重放/竞态漏洞、未经授权的自动化、价格更新函数或其他技术弱点来制造价值、改变债务或抵押状态、操纵价格、绕过限制、隐藏漏洞所得或协助被禁止的现实货币交易。TycoonX自行运行的价格自动化属于正常游戏机制，并非玩家使用机器人。巨额盈利或亏损、大额交易、高额债务或异常行情本身不足以证明滥用；因授权或验证缺陷而被服务器接受的请求，也不会让明知被操纵的状态自动变为合法。`,
      `游戏内债务可依据当时有效规则影响符合条件的虚拟游戏资产，但仅有游戏债务并不会使无关且有效购买的Diamonds、一次性30天VIP或Lifetime VIP自动成为抵押物。用于解锁符合条件外汇栏位的Diamonds购买的是游戏内栏位权益，而非投资盈利承诺。过期界面、可受客户端影响的记录以及便利通知均不当然属于最终证据。CK-Labs应区分服务中断、技术缺陷、一次性意外行为、账号被盗与明知或反复利用漏洞，并仅按比例纠正直接受影响的无效状态，同时保留所有强制性消费者权利及其他不可放弃的权利。`,
    ],
  },
  zh_Hans: {
    label: '游戏规则说明 · 2026年9月10日',
    title: '银行、信贷、外汇、股票和加密资产均为游戏内虚拟系统',
    paragraphs: [
      `TycoonX中的银行、储蓄、信贷、外汇、股票和加密资产是虚构的经营模拟机制，不是真实银行存款、证券、投资产品、法定货币或现实加密资产。正常利息、借款、逾期、抵押后果、破产、交易、盈利和亏损都属于游戏结果，本身不会自动构成违规。利率、信贷规则、抵押估值、冷却时间、费用、点差和市场公式可因合理的游戏原因面向未来调整，但适用的强制性通知、变更、合规或终止权利不受影响。显示的收益率、报价、图表或趋势不保证未来表现。`,
      `请勿利用修改版客户端、直接API、你控制的账号、伪造持仓或交易/历史记录、循环交易或洗售、重放/竞态漏洞、未经授权的自动化、价格更新函数或其他技术弱点来制造价值、改变债务或抵押状态、操纵价格、绕过限制、隐藏漏洞所得或协助被禁止的现实货币交易。TycoonX自行运行的价格自动化是正常游戏机制，并非玩家机器人。巨额盈亏、大额交易、高额债务或异常行情本身不足以证明滥用；服务器因授权或验证缺陷接受请求，也不会让明知被操纵的状态自动变得合法。`,
      `游戏内债务可按当时有效规则影响符合条件的虚拟游戏资产，但仅因游戏债务不会让无关且有效购买的Diamonds、一次性30天VIP或Lifetime VIP自动成为抵押物。用于解锁符合条件外汇栏位的Diamonds购买的是游戏内栏位权益，不是投资盈利承诺。过期界面、可受客户端影响的记录和便利通知并不当然属于最终证据。CK-Labs应区分服务中断、技术缺陷、一次性意外行为、账号被盗与明知或反复利用漏洞，只按比例纠正直接受影响的无效状态，并保留所有强制性消费者权利和其他不可放弃的权利。`,
    ],
  },
  zh_Hant: {
    label: '遊戲規則說明 · 2026年9月10日',
    title: '銀行、信貸、外匯、股票與加密資產均為遊戲內虛擬系統',
    paragraphs: [
      `TycoonX中的銀行、儲蓄、信貸、外匯、股票與加密資產是虛構的經營模擬機制，不是真實銀行存款、證券、投資產品、法定貨幣或現實加密資產。正常利息、借款、逾期、抵押後果、破產、交易、獲利與虧損都屬於遊戲結果，本身不會自動構成違規。利率、信貸規則、抵押估值、冷卻時間、費用、價差與市場公式可基於合理的遊戲原因面向未來調整，但適用的強制性通知、變更、合規或終止權利不受影響。顯示的收益率、報價、圖表或趨勢不保證未來表現。`,
      `請勿利用修改版用戶端、直接API、你控制的帳號、偽造持倉或交易/歷史紀錄、循環交易或洗售、重放/競態漏洞、未經授權的自動化、價格更新函式或其他技術弱點來製造價值、改變債務或抵押狀態、操縱價格、繞過限制、隱藏漏洞所得或協助被禁止的現實貨幣交易。TycoonX自行運行的價格自動化是正常遊戲機制，並非玩家機器人。巨額盈虧、大額交易、高額債務或異常行情本身不足以證明濫用；伺服器因授權或驗證缺陷接受請求，也不會讓明知被操縱的狀態自動變得合法。`,
      `遊戲內債務可按當時有效規則影響符合條件的虛擬遊戲資產，但僅因遊戲債務不會讓無關且有效購買的Diamonds、一次性30天VIP或Lifetime VIP自動成為抵押物。用於解鎖符合條件外匯欄位的Diamonds購買的是遊戲內欄位權益，不是投資獲利承諾。過期畫面、可受用戶端影響的紀錄與便利通知並不當然屬於最終證據。CK-Labs應區分服務中斷、技術缺陷、一次性意外行為、帳號遭入侵與明知或反覆利用漏洞，只按比例修正直接受影響的無效狀態，並保留所有強制性消費者權利及其他不可放棄的權利。`,
    ],
  },
  ar: {
    label: 'توضيح بشأن أسلوب اللعب · 10 سبتمبر 2026',
    title: 'البنك والائتمان والعملات والأسهم والعملات المشفرة أنظمة افتراضية داخل اللعبة',
    paragraphs: [
      `البنك والادخار والائتمان وتداول العملات والأسهم والعملات المشفرة في TycoonX هي آليات محاكاة خيالية، وليست ودائع مصرفية حقيقية أو أوراقاً مالية أو استثمارات أو عملة قانونية أو أصولاً مشفرة حقيقية. الفائدة العادية والاقتراض والتأخر في السداد وآثار الضمان والإفلاس والتداول والأرباح والخسائر هي نتائج داخل اللعبة ولا تعد مخالفة تلقائياً. يجوز إعادة موازنة المعدلات وقواعد الائتمان وقيم الضمان وفترات الانتظار والرسوم وفروق الأسعار ومعادلات السوق مستقبلاً لأسباب مشروعة تتعلق باللعبة، مع بقاء أي حقوق إلزامية واجبة التطبيق بشأن الإخطار أو التغيير أو المطابقة أو الإنهاء. لا يضمن أي عائد أو سعر أو رسم بياني أو اتجاه معروض أداءً مستقبلياً.`,
      `لا تستخدم عميلاً معدلاً أو واجهات API مباشرة أو حسابات تسيطر عليها أو أرصدة أو سجلات تداول/تاريخ مختلقة أو تداولاً دائرياً أو wash trading أو أخطاء replay/race أو أتمتة غير مصرح بها أو وظائف تحديث الأسعار أو أي ثغرة تقنية أخرى لإنشاء قيمة أو تغيير دين أو ضمان أو التلاعب بالأسعار أو تجاوز الحدود أو إخفاء عائدات الاستغلال أو تسهيل تجارة محظورة بأموال حقيقية. أتمتة الأسعار التي تديرها TycoonX جزء مقصود من اللعبة وليست روبوتاً يستخدمه اللاعب. الربح أو الخسارة الكبيرة أو الصفقة الكبيرة أو الدين المرتفع أو حركة السوق غير المعتادة لا تثبت إساءة الاستخدام وحدها، كما أن قبول الخادم لطلب بسبب خلل في التفويض أو التحقق لا يجعل الحالة المتلاعب بها عن علم مشروعة.`,
      `قد يؤثر الدين داخل اللعبة في الأصول الافتراضية المؤهلة وفق القواعد السارية آنذاك، لكنه لا يجعل وحده Diamonds المشتراة بشكل صحيح وغير المرتبطة، أو VIP لمدة 30 يوماً لمرة واحدة، أو Lifetime VIP ضماناً للدين. إنفاق Diamonds لفتح خانة مؤهلة لتداول العملات يشتري حق الخانة داخل اللعبة ولا يعد وعداً بربح استثماري. الشاشات القديمة والسجلات التي يمكن للعميل التأثير فيها وإشعارات التذكير ليست دليلاً حاسماً تلقائياً. ينبغي لـ CK-Labs التمييز بين الانقطاعات والعيوب التقنية والتصرفات العرضية لمرة واحدة واختراق الحساب من جهة، والاستغلال المتعمد أو المتكرر من جهة أخرى، وتصحيح الحالة غير الصحيحة المتأثرة مباشرة بشكل متناسب، مع الحفاظ على جميع حقوق المستهلك الإلزامية وغيرها من الحقوق التي لا يجوز التنازل عنها.`,
    ],
  },
  nl: {
    label: 'Gameplay-toelichting · 10 september 2026',
    title: 'Bankieren, krediet, valuta, aandelen en crypto zijn virtuele spelsystemen',
    paragraphs: [
      `Bankieren, sparen, krediet, valuta, aandelen en crypto in TycoonX zijn fictieve simulatiemechanieken, geen echte bankdeposito's, effecten, beleggingen, wettig betaalmiddel of echte cryptoactiva. Normale rente, leningen, betalingsachterstand, gevolgen voor onderpand, faillissement, transacties, winst en verlies zijn speluitkomsten en vormen niet automatisch een overtreding. Rentes, kredietregels, onderpandwaarden, wachttijden, kosten, spreads en marktformules kunnen voor de toekomst om legitieme spelredenen worden aangepast, met behoud van toepasselijke dwingende rechten over informatie, wijziging, conformiteit of beëindiging. Geen getoond rendement, koers, grafiek of trend garandeert toekomstige prestaties.`,
      `Gebruik geen aangepaste clients, directe API's, accounts die je beheert, verzonnen posities of transactie-/historiegegevens, wash- of circulaire handel, replay-/racebugs, ongeautoriseerde automatisering, prijsupdatefuncties of andere technische zwaktes om waarde te creëren, schuld of onderpand te wijzigen, prijzen te manipuleren, limieten te omzeilen, exploitopbrengsten te verbergen of verboden handel voor echt geld mogelijk te maken. Door TycoonX zelf beheerde prijsautomatisering is een bedoelde spelmechaniek en geen spelerbot. Een grote winst of verlies, grote transactie, hoge schuld of ongebruikelijke marktbeweging bewijst op zichzelf geen misbruik; serveracceptatie door een autorisatie- of validatiefout maakt bewust gemanipuleerde toestand evenmin legitiem.`,
      `Spelschuld kan volgens de dan geldende regels geschikte virtuele spelactiva raken, maar maakt op zichzelf niet-gerelateerde geldig gekochte Diamonds, eenmalige 30-Day VIP of Lifetime VIP niet tot onderpand. Diamonds voor het ontgrendelen van een geschikt valutaslot kopen dat recht in het spel, geen belofte van beleggingswinst. Verouderde schermen, door de client beïnvloedbare gegevens en gemaksnotificaties zijn niet automatisch doorslaggevend bewijs. CK-Labs moet storingen, defecten, eenmalige vergissingen en gecompromitteerde accounts onderscheiden van bewuste of herhaalde exploitatie, direct getroffen ongeldige toestand evenredig corrigeren en alle dwingende consumentenrechten en andere rechten waarvan niet kan worden afgeweken behouden.`,
    ],
  },
  sv: {
    label: 'Förtydligande om spelmekanik · 10 september 2026',
    title: 'Bank, kredit, valuta, aktier och krypto är virtuella spelsystem',
    paragraphs: [
      `Bank, sparande, kredit, valuta, aktier och krypto i TycoonX är fiktiva simuleringsmekaniker, inte riktiga bankinsättningar, värdepapper, investeringar, lagliga betalningsmedel eller verkliga kryptotillgångar. Normal ränta, lån, sena betalningar, följder för säkerheter, konkurs, handel, vinster och förluster är spelutfall och innebär inte automatiskt regelbrott. Räntor, kreditregler, säkerhetsvärden, väntetider, avgifter, spreadar och marknadsformler kan balanseras om framåt av legitima spelskäl, med bibehållande av tvingande rättigheter om information, ändringar, avtalsenlighet eller uppsägning där de gäller. Ingen visad avkastning, kurs, graf eller trend garanterar framtida resultat.`,
      `Använd inte modifierade klienter, direkta API:er, konton du kontrollerar, fabricerade innehav eller transaktions-/historikposter, wash- eller cirkulär handel, replay-/racebuggar, otillåten automatisering, prisuppdateringsfunktioner eller andra tekniska svagheter för att skapa värde, ändra skuld eller säkerhet, manipulera priser, kringgå gränser, dölja exploitvinster eller underlätta förbjuden handel för riktiga pengar. Prisautomatik som drivs av TycoonX är en avsedd spelmekanik och inte spelarbotting. En stor vinst eller förlust, stor affär, hög skuld eller ovanlig marknadsrörelse bevisar inte missbruk i sig; att servern godtar en begäran på grund av ett behörighets- eller valideringsfel gör inte heller ett medvetet manipulerat tillstånd legitimt.`,
      `Spelskuld kan påverka kvalificerade virtuella speltillgångar enligt de regler som då gäller, men gör inte i sig orelaterade giltigt köpta Diamonds, engångs-VIP i 30 dagar eller Lifetime VIP till säkerhet. Diamonds som används för att låsa upp en kvalificerad valutaplats köper den spelrätten, inte ett löfte om investeringsvinst. Föråldrade skärmar, klientpåverkbara poster och praktiska aviseringar är inte automatiskt avgörande bevis. CK-Labs ska skilja driftstopp, tekniska fel, enstaka misstag och komprometterade konton från medvetet eller upprepat utnyttjande, proportionerligt korrigera direkt berört ogiltigt tillstånd och bevara alla tvingande konsumenträttigheter och andra rättigheter som inte kan avtalas bort.`,
    ],
  },
  nb: {
    label: 'Avklaring om spillmekanikk · 10. september 2026',
    title: 'Bank, kreditt, valuta, aksjer og krypto er virtuelle spillsystemer',
    paragraphs: [
      `Bank, sparing, kreditt, valuta, aksjer og krypto i TycoonX er fiktive simuleringsmekanikker, ikke ekte bankinnskudd, verdipapirer, investeringer, lovlige betalingsmidler eller reelle kryptoaktiva. Vanlige renter, lån, forsinket betaling, følger for sikkerhet, konkurs, handler, gevinst og tap er spillutfall og er ikke automatisk regelbrudd. Renter, kredittregler, sikkerhetsverdier, ventetider, gebyrer, spreader og markedsformler kan balanseres fremover av legitime spillgrunner, med forbehold for ufravikelige rettigheter om informasjon, endringer, kontraktsmessighet eller oppsigelse der de gjelder. Ingen vist avkastning, kurs, graf eller trend garanterer fremtidig resultat.`,
      `Ikke bruk modifiserte klienter, direkte API-er, kontoer du kontrollerer, oppdiktede beholdninger eller transaksjons-/historikkdata, wash- eller sirkulær handel, replay-/race-feil, uautorisert automatisering, prisoppdateringsfunksjoner eller andre tekniske svakheter for å skape verdi, endre gjeld eller sikkerhet, manipulere priser, omgå grenser, skjule exploit-utbytte eller legge til rette for forbudt handel med ekte penger. Prisautomatisering drevet av TycoonX er en tiltenkt spillmekanikk og ikke spillerbotting. Stor gevinst eller tap, stor handel, høy gjeld eller uvanlig markedsbevegelse beviser ikke misbruk alene; at serveren godtar en forespørsel på grunn av en autorisasjons- eller valideringsfeil gjør heller ikke bevisst manipulert tilstand legitim.`,
      `Spillgjeld kan påvirke kvalifiserte virtuelle spilleiendeler etter reglene som gjelder da, men gjør ikke i seg selv urelaterte og gyldig kjøpte Diamonds, engangs 30-dagers VIP eller Lifetime VIP til sikkerhet. Diamonds brukt til å låse opp en kvalifisert valutaplass kjøper spillretten, ikke et løfte om investeringsgevinst. Utdaterte skjermer, klientpåvirkbare poster og praktiske varsler er ikke automatisk avgjørende bevis. CK-Labs skal skille driftsavbrudd, tekniske feil, enkelttilfeller ved uhell og kompromitterte kontoer fra bevisst eller gjentatt utnyttelse, korrigere direkte berørt ugyldig tilstand forholdsmessig og bevare alle ufravikelige forbrukerrettigheter og andre rettigheter som ikke kan fravikes.`,
    ],
  },
  pl: {
    label: 'Wyjaśnienie zasad rozgrywki · 10 września 2026 r.',
    title: 'Bank, kredyt, waluty, akcje i krypto to wirtualne systemy gry',
    paragraphs: [
      `Bank, oszczędności, kredyt, waluty, akcje i krypto w TycoonX są fikcyjnymi mechanikami symulacji, a nie prawdziwymi depozytami bankowymi, papierami wartościowymi, inwestycjami, prawnym środkiem płatniczym ani rzeczywistymi kryptoaktywami. Zwykłe odsetki, pożyczki, opóźnienia w płatności, skutki dotyczące zabezpieczenia, bankructwo, transakcje, zyski i straty są wynikami rozgrywki i nie stanowią automatycznie naruszenia. Stopy, zasady kredytowe, wyceny zabezpieczeń, czasy oczekiwania, opłaty, spready i formuły rynkowe mogą być zmieniane na przyszłość z uzasadnionych powodów dotyczących gry, z zachowaniem obowiązkowych praw do informacji, zmian, zgodności lub rozwiązania umowy, jeśli mają zastosowanie. Żadna wyświetlana stopa zwrotu, cena, wykres ani trend nie gwarantuje przyszłych wyników.`,
      `Nie używaj zmodyfikowanych klientów, bezpośrednich API, kontrolowanych przez siebie kont, sfabrykowanych pozycji lub historii transakcji, wash tradingu lub transakcji okrężnych, błędów replay/race, nieautoryzowanej automatyzacji, funkcji aktualizacji cen ani innych słabości technicznych do tworzenia wartości, zmiany długu lub zabezpieczenia, manipulowania cenami, obchodzenia limitów, ukrywania korzyści z exploitów albo ułatwiania zakazanego handlu za prawdziwe pieniądze. Automatyzacja cen prowadzona przez TycoonX jest zamierzoną mechaniką gry, a nie botem gracza. Duży zysk lub strata, duża transakcja, wysoki dług czy nietypowy ruch rynku same nie dowodzą nadużycia; zaakceptowanie żądania przez serwer z powodu błędu autoryzacji lub walidacji również nie legalizuje świadomie zmanipulowanego stanu.`,
      `Dług w grze może wpływać na kwalifikujące się wirtualne aktywa zgodnie z aktualnymi zasadami, lecz sam nie czyni zabezpieczeniem niezwiązanych, ważnie kupionych Diamonds, jednorazowego VIP na 30 dni ani Lifetime VIP. Diamonds wykorzystane do odblokowania kwalifikującego się slotu walutowego kupują to uprawnienie w grze, a nie obietnicę zysku inwestycyjnego. Nieaktualne ekrany, dane podatne na wpływ klienta i pomocnicze powiadomienia nie są automatycznie rozstrzygającym dowodem. CK-Labs powinna odróżniać awarie, błędy techniczne, jednorazowe przypadkowe działania i przejęte konta od świadomego lub powtarzanego wykorzystywania luk, proporcjonalnie korygować bezpośrednio dotknięty nieważny stan i zachować wszystkie bezwzględnie obowiązujące prawa konsumenta oraz inne prawa, których nie można się zrzec.`,
    ],
  },
  th: {
    label: 'คำชี้แจงเกี่ยวกับเกม · 10 กันยายน 2026',
    title: 'ธนาคาร เครดิต FX หุ้น และคริปโตเป็นระบบเสมือนภายในเกม',
    paragraphs: [
      `ธนาคาร เงินออม เครดิต FX หุ้น และคริปโตใน TycoonX เป็นกลไกจำลองทางธุรกิจที่สมมติขึ้น ไม่ใช่เงินฝากธนาคาร หลักทรัพย์ การลงทุน เงินที่ชำระหนี้ได้ตามกฎหมาย หรือสินทรัพย์คริปโตจริง ดอกเบี้ยปกติ การกู้ยืม การชำระล่าช้า ผลต่อหลักประกัน การล้มละลาย การซื้อขาย กำไรและขาดทุนเป็นผลของเกมและไม่ได้เป็นการฝ่าฝืนโดยอัตโนมัติ อัตรา กฎเครดิต มูลค่าหลักประกัน คูลดาวน์ ค่าธรรมเนียม สเปรด และสูตรตลาดอาจปรับสมดุลสำหรับอนาคตด้วยเหตุผลที่ชอบด้วยเกม โดยยังคงสิทธิที่กฎหมายบังคับเกี่ยวกับการแจ้ง การเปลี่ยนแปลง ความสอดคล้อง หรือการยุติหากมีผลใช้บังคับ ผลตอบแทน ราคา กราฟ หรือแนวโน้มที่แสดงไม่รับประกันผลในอนาคต`,
      `ห้ามใช้ไคลเอนต์ดัดแปลง API โดยตรง บัญชีที่คุณควบคุม สถานะถือครองหรือประวัติธุรกรรมปลอม การซื้อขายวนหรือ wash trading บั๊ก replay/race ระบบอัตโนมัติที่ไม่ได้รับอนุญาต ฟังก์ชันอัปเดตราคา หรือจุดอ่อนทางเทคนิคอื่นเพื่อสร้างมูลค่า เปลี่ยนหนี้หรือหลักประกัน ปั่นราคา เลี่ยงข้อจำกัด ซ่อนผลประโยชน์จาก exploit หรือช่วยการซื้อขายด้วยเงินจริงที่ห้ามไว้ ระบบปรับราคาอัตโนมัติที่ TycoonX ดำเนินการเป็นกลไกเกมที่ตั้งใจไว้ ไม่ใช่บอตของผู้เล่น กำไรหรือขาดทุนจำนวนมาก ธุรกรรมใหญ่ หนี้สูง หรือการเคลื่อนไหวตลาดผิดปกติเพียงอย่างเดียวไม่พิสูจน์การละเมิด และการที่เซิร์ฟเวอร์รับคำขอเพราะข้อบกพร่องด้านสิทธิหรือการตรวจสอบก็ไม่ได้ทำให้สถานะที่จงใจบิดเบือนกลายเป็นถูกต้อง`,
      `หนี้ในเกมอาจกระทบสินทรัพย์เสมือนที่เข้าเกณฑ์ตามกฎที่ใช้ในขณะนั้น แต่หนี้ในเกมเพียงอย่างเดียวไม่ทำให้ Diamonds ที่ซื้ออย่างถูกต้องและไม่เกี่ยวข้อง VIP 30 วันแบบครั้งเดียว หรือ Lifetime VIP กลายเป็นหลักประกัน Diamonds ที่ใช้ปลดล็อกช่อง FX ที่เข้าเกณฑ์ซื้อสิทธิช่องในเกม ไม่ใช่คำมั่นว่าจะได้กำไรจากการลงทุน หน้าจอที่ล้าสมัย บันทึกที่ไคลเอนต์อาจมีอิทธิพล และการแจ้งเตือนเพื่อความสะดวกไม่ได้เป็นหลักฐานสรุปเด็ดขาดโดยอัตโนมัติ CK-Labs ควรแยกเหตุขัดข้อง ข้อบกพร่อง การกระทำโดยบังเอิญครั้งเดียว และบัญชีถูกยึดจากการใช้ช่องโหว่โดยรู้ตัวหรือซ้ำ ๆ แก้ไขเฉพาะสถานะที่ไม่ถูกต้องซึ่งได้รับผลโดยตรงอย่างได้สัดส่วน และรักษาสิทธิผู้บริโภคที่กฎหมายบังคับและสิทธิอื่นที่สละไม่ได้ทั้งหมด`,
    ],
  },
  vi: {
    label: 'Làm rõ về lối chơi · 10/09/2026',
    title: 'Ngân hàng, tín dụng, ngoại hối, cổ phiếu và crypto là hệ thống ảo trong game',
    paragraphs: [
      `Ngân hàng, tiết kiệm, tín dụng, ngoại hối, cổ phiếu và crypto trong TycoonX là cơ chế mô phỏng hư cấu, không phải tiền gửi ngân hàng, chứng khoán, khoản đầu tư, tiền pháp định hay tài sản crypto ngoài đời. Tiền lãi thông thường, vay nợ, trả chậm, hậu quả đối với tài sản bảo đảm, phá sản, giao dịch, lãi và lỗ đều là kết quả của gameplay và không tự động là hành vi vi phạm. Lãi suất, quy tắc tín dụng, giá trị tài sản bảo đảm, thời gian chờ, phí, chênh lệch và công thức thị trường có thể được cân bằng lại cho tương lai vì lý do chính đáng của trò chơi, nhưng các quyền bắt buộc về thông báo, thay đổi, tính phù hợp hoặc chấm dứt vẫn được giữ nguyên nếu áp dụng. Lợi suất, giá, biểu đồ hay xu hướng hiển thị không bảo đảm kết quả trong tương lai.`,
      `Không được dùng client đã sửa đổi, API trực tiếp, tài khoản do bạn kiểm soát, vị thế hay lịch sử giao dịch giả, wash trading hoặc giao dịch vòng tròn, lỗi replay/race, tự động hóa trái phép, hàm cập nhật giá hoặc điểm yếu kỹ thuật khác để tạo giá trị, thay đổi nợ hay tài sản bảo đảm, thao túng giá, vượt giới hạn, che giấu lợi ích từ exploit hoặc hỗ trợ giao dịch tiền thật bị cấm. Tự động hóa giá do TycoonX vận hành là cơ chế game được thiết kế sẵn, không phải bot của người chơi. Lợi nhuận hay thua lỗ lớn, giao dịch lớn, nợ cao hoặc biến động thị trường bất thường tự nó không chứng minh hành vi lạm dụng; việc máy chủ chấp nhận yêu cầu do lỗi phân quyền hoặc xác thực cũng không biến trạng thái bị cố ý thao túng thành hợp lệ.`,
      `Nợ trong game có thể ảnh hưởng đến tài sản ảo đủ điều kiện theo quy tắc đang áp dụng, nhưng bản thân nợ gameplay không tự biến Diamonds đã mua hợp lệ và không liên quan, VIP 30 ngày dùng một lần hoặc Lifetime VIP thành tài sản bảo đảm. Diamonds dùng để mở một ô FX đủ điều kiện mua quyền sử dụng ô đó trong game, không phải lời hứa lợi nhuận đầu tư. Màn hình lỗi thời, dữ liệu mà client có thể tác động và thông báo tiện ích không tự động là bằng chứng kết luận. CK-Labs phải phân biệt sự cố, lỗi kỹ thuật, hành động vô ý đơn lẻ và tài khoản bị xâm nhập với việc cố ý hoặc lặp lại khai thác lỗi, sửa trạng thái không hợp lệ bị ảnh hưởng trực tiếp một cách tương xứng và bảo lưu mọi quyền bắt buộc của người tiêu dùng cũng như các quyền không thể từ bỏ khác.`,
    ],
  },
  uk: {
    label: 'Уточнення правил гри · 10 вересня 2026 р.',
    title: 'Банк, кредит, валюти, акції та криптоактиви є віртуальними системами гри',
    paragraphs: [
      `Банк, заощадження, кредит, валюти, акції та криптоактиви в TycoonX є вигаданими механіками економічної симуляції, а не справжніми банківськими вкладами, цінними паперами, інвестиціями, законним платіжним засобом чи реальними криптоактивами. Звичайні відсотки, позики, прострочення, наслідки для застави, банкрутство, угоди, прибутки та збитки є результатами гри й самі по собі не означають порушення. Ставки, кредитні правила, вартість застави, періоди очікування, комісії, спреди та ринкові формули можуть змінюватися на майбутнє з обґрунтованих ігрових причин зі збереженням обов'язкових прав на повідомлення, зміну, відповідність чи припинення договору, якщо вони застосовуються. Показана дохідність, ціна, графік або тренд не гарантують майбутнього результату.`,
      `Не використовуйте модифіковані клієнти, прямі API, контрольовані вами акаунти, сфабриковані позиції чи записи угод/історії, wash trading або кругові угоди, помилки replay/race, несанкціоновану автоматизацію, функції оновлення цін чи інші технічні слабкості для створення цінності, зміни боргу або застави, маніпуляції цінами, обходу лімітів, приховування вигоди від експлойтів чи сприяння забороненій торгівлі за реальні гроші. Автоматизація цін, яку запускає TycoonX, є передбаченою механікою гри, а не ботом гравця. Великий прибуток або збиток, велика угода, високий борг чи незвичний рух ринку самі по собі не доводять зловживання; прийняття сервером запиту через помилку авторизації чи перевірки також не робить свідомо підроблений стан правомірним.`,
      `Ігровий борг може впливати на відповідні віртуальні активи за правилами, чинними на той час, але сам по собі не робить заставою не пов'язані з ним і дійсно придбані Diamonds, одноразовий 30-денний VIP або Lifetime VIP. Diamonds, витрачені на відкриття доступного валютного слота, купують право на цей слот у грі, а не обіцянку інвестиційного прибутку. Застарілі екрани, записи, на які може впливати клієнт, та сервісні сповіщення не є автоматично остаточним доказом. CK-Labs має відрізняти збої, технічні дефекти, одноразові випадкові дії та компрометацію акаунта від свідомого або повторного використання вразливостей, пропорційно виправляти безпосередньо зачеплений недійсний стан і зберігати всі обов'язкові права споживачів та інші права, від яких не можна відмовитися.`,
    ],
  },
  hi: {
    label: 'गेमप्ले स्पष्टीकरण · 10 सितंबर 2026',
    title: 'बैंकिंग, क्रेडिट, FX, स्टॉक और क्रिप्टो गेम के वर्चुअल सिस्टम हैं',
    paragraphs: [
      `TycoonX में बैंकिंग, बचत, क्रेडिट, FX, स्टॉक और क्रिप्टो काल्पनिक सिमुलेशन मैकेनिक्स हैं; वे वास्तविक बैंक जमा, सिक्योरिटीज, निवेश, कानूनी मुद्रा या वास्तविक क्रिप्टो एसेट नहीं हैं। सामान्य ब्याज, उधार, देर से भुगतान, कोलेटरल के परिणाम, दिवालियापन, ट्रेड, लाभ और हानि गेमप्ले के परिणाम हैं और अपने आप नियम उल्लंघन नहीं हैं। ब्याज दरें, क्रेडिट नियम, कोलेटरल मूल्य, कूलडाउन, फीस, स्प्रेड और मार्केट फ़ॉर्मूले वैध गेम कारणों से आगे के लिए रीबैलेंस किए जा सकते हैं, लेकिन लागू होने वाले अनिवार्य सूचना, बदलाव, अनुरूपता या समाप्ति अधिकार बने रहते हैं। स्क्रीन पर दिखने वाला कोई यील्ड, भाव, चार्ट या ट्रेंड भविष्य के प्रदर्शन की गारंटी नहीं देता।`,
      `वैल्यू बनाने, कर्ज या कोलेटरल की स्थिति बदलने, कीमतें प्रभावित करने, सीमा से बचने, exploit से मिली वैल्यू छिपाने या प्रतिबंधित असली-पैसे के व्यापार को आसान बनाने के लिए modified client, direct API, आपके नियंत्रण वाले खाते, नकली holdings या transaction/history records, wash या circular trading, replay/race bugs, अनधिकृत automation, price-update functions या दूसरी तकनीकी कमजोरियों का इस्तेमाल न करें। TycoonX द्वारा चलाया गया price automation गेम का तय हिस्सा है, खिलाड़ी का bot नहीं। बड़ा लाभ या नुकसान, बड़ा ट्रेड, ज्यादा कर्ज या असामान्य बाजार चाल अकेले abuse का सबूत नहीं है; authorization या validation defect के कारण server का request स्वीकार करना भी जानबूझकर बदली गई state को वैध नहीं बनाता।`,
      `गेम का कर्ज उस समय लागू नियमों के अनुसार योग्य virtual game assets को प्रभावित कर सकता है, लेकिन केवल कर्ज होने से असंबंधित और वैध रूप से खरीदे गए Diamonds, one-time 30-Day VIP या Lifetime VIP कोलेटरल नहीं बन जाते। योग्य FX slot खोलने में खर्च किए गए Diamonds उस in-game slot का अधिकार खरीदते हैं, निवेश लाभ का वादा नहीं। पुराने screens, client से प्रभावित हो सकने वाले records और convenience notifications अपने आप निर्णायक प्रमाण नहीं हैं। CK-Labs को outages, technical defects, एक बार की accidental actions और compromised accounts को जानबूझकर या बार-बार exploit करने से अलग करना चाहिए, सीधे प्रभावित invalid state को अनुपातिक रूप से ठीक करना चाहिए और सभी अनिवार्य consumer rights तथा अन्य non-waivable rights सुरक्षित रखने चाहिए।`,
    ],
  },
  id: {
    label: 'Penjelasan gameplay · 10 September 2026',
    title: 'Bank, kredit, valuta, saham, dan kripto adalah sistem virtual dalam game',
    paragraphs: [
      `Bank, tabungan, kredit, valuta asing, saham, dan kripto di TycoonX adalah mekanik simulasi fiktif, bukan simpanan bank nyata, efek, investasi, alat pembayaran yang sah, atau aset kripto nyata. Bunga normal, pinjaman, keterlambatan pembayaran, konsekuensi agunan, kebangkrutan, perdagangan, keuntungan, dan kerugian merupakan hasil gameplay dan tidak otomatis menjadi pelanggaran. Suku bunga, aturan kredit, nilai agunan, cooldown, biaya, spread, dan formula pasar dapat diseimbangkan ulang untuk masa depan demi alasan game yang sah, dengan tetap menghormati hak wajib yang berlaku terkait pemberitahuan, perubahan, kesesuaian, atau penghentian. Imbal hasil, harga, grafik, atau tren yang ditampilkan tidak menjamin hasil di masa depan.`,
      `Jangan gunakan client yang dimodifikasi, API langsung, akun yang Anda kendalikan, kepemilikan atau catatan transaksi/riwayat palsu, wash trading atau transaksi melingkar, bug replay/race, otomatisasi tanpa izin, fungsi pembaruan harga, atau kelemahan teknis lain untuk menciptakan nilai, mengubah utang atau agunan, memanipulasi harga, menghindari batas, menyembunyikan hasil exploit, atau memfasilitasi perdagangan uang nyata yang dilarang. Otomatisasi harga yang dijalankan TycoonX adalah mekanik resmi game, bukan bot pemain. Keuntungan atau kerugian besar, transaksi besar, utang tinggi, atau pergerakan pasar yang tidak biasa saja tidak membuktikan penyalahgunaan; permintaan yang diterima server karena cacat otorisasi atau validasi juga tidak membuat state yang sengaja dimanipulasi menjadi sah.`,
      `Utang dalam game dapat memengaruhi aset virtual yang memenuhi syarat berdasarkan aturan yang berlaku saat itu, tetapi utang gameplay saja tidak menjadikan Diamonds yang dibeli secara sah dan tidak terkait, VIP 30 hari sekali beli, atau Lifetime VIP sebagai agunan. Diamonds yang dipakai untuk membuka slot FX yang memenuhi syarat membeli hak slot dalam game tersebut, bukan janji keuntungan investasi. Tampilan lama, catatan yang dapat dipengaruhi client, dan notifikasi kenyamanan tidak otomatis menjadi bukti akhir. CK-Labs harus membedakan gangguan, cacat teknis, tindakan tidak sengaja satu kali, dan akun yang disusupi dari exploit yang disengaja atau berulang, memperbaiki state tidak sah yang terdampak langsung secara proporsional, serta menjaga seluruh hak konsumen wajib dan hak lain yang tidak dapat dikesampingkan.`,
    ],
  },
};

function getLocale(pathname: string): string | null {
  if (/^\/tyconx-terms-of-service\/?$/.test(pathname)) return 'en';
  const match = pathname.match(/^\/tycoonx-legal\/([^/]+)\/terms\/?$/);
  return match?.[1] ?? null;
}

function htmlLang(locale: string): string {
  const mapped: Record<string, string> = {
    es_MX: 'es-MX',
    fr_CA: 'fr-CA',
    pt_BR: 'pt-BR',
    zh_Hans: 'zh-Hans',
    zh_Hant: 'zh-Hant',
  };
  return mapped[locale] ?? locale;
}

export default function BankCreditMarketsRuleNotice() {
  const pathname = usePathname();
  const locale = getLocale(pathname);
  if (!locale || !copies[locale]) return null;

  const copy = copies[locale];
  const rtl = locale === 'ar';

  return (
    <section className="max-w-3xl mx-auto px-4 pb-12" lang={htmlLang(locale)} dir={rtl ? 'rtl' : 'ltr'} aria-labelledby="tycoonx-bank-credit-markets-rule-heading">
      <div className="rounded-xl border border-amber-400/20 bg-amber-400/[0.05] p-6">
        <p className="text-amber-300/80 text-xs font-medium tracking-wide mb-2">{copy.label}</p>
        <h2 id="tycoonx-bank-credit-markets-rule-heading" className="text-white font-semibold mb-4">{copy.title}</h2>
        <div className="space-y-3 text-zinc-400 text-sm leading-relaxed">
          {copy.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
        </div>
      </div>
    </section>
  );
}
